name: jall_flutter
description: Jall Ride Booking App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1

flutter:
  uses-material-design: true
